Szakdoga/Controllers/UzenetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Szakdoga.Models;

namespace Szakdoga.Controllers
{
    public class UzenetController : Controller
    {
        // GET: Uzenet
        readonly ApplicationDbContext _context;
        public UzenetController() => _context = new ApplicationDbContext();

        public ActionResult Index()
        {
            var message = _context.Messages.ToList().OrderByDescending(f => f.Id);
            return View(message);
        }
        public ActionResult New()
        {
            return View("New");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Mentes(Message message)
        {
            if (!ModelState.IsValid)
            {
                var vm = new MessageModel
                {
                    Message = message
                };
                return View("New", vm);
            }

            if (message.Id == null || message.Id == 0)
            {
                message.Lattamozott = false;
                _context.Messages.Add(message);
            }
            _context.SaveChanges();
            return RedirectToAction("Calendar", "Home");
        }
    }
}

Szakdoga/Views/Uzenet/New.cshtml
@model Szakdoga.Models.MessageModel
@{
    ViewBag.Title = "Üzenet írása";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row justify-content-center align-items-center">
    <div class="card">
        <div class="col-md-offset-12 col-md-12 text-center">
            <br />
            <h1 class="home-title">
                <span>Írj módosítás kérelmet!</span>
            </h1>
        </div>
        <div class="card-body">

            @using (Html.BeginForm("Mentes", "Uzenet", FormMethod.Post))
            { 
            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-12">

                        <input name="Message.Email" class="effect-2" type="email" id="Message.Email" placeholder="E-mail címed">
                        <span class="focus-border"></span><br />
                    </div>
                </div>
            </div>

                <div class="form-group ">

                    <label for="Message_Velemeny" style="margin-bottom: 10px; margin-left:15px">Szöveg:</label>
                    <textarea class="form-control" cols="20" id="Message_Szoveg" name="Message.Velemeny" style="height:100px; width:100%; margin-left:5px; "></textarea>
                    @Html.ValidationMessageFor(m => m.Message.Velemeny)
                </div>
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <br />

                @Html.HiddenFor(m => m.Message.Id)
                @Html.AntiForgeryToken()
                <div class="col-md-offset-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-default" style="border: 1px solid black" ;">Küldés</button>
                    </div>
                    }

                </div>
            </div>
</div>