Szakdoga/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Szakdoga.Models
{
    public class Message
    {
        public int? Id { get; set; }
        public string Email { get; set; }
        [Required]
        public string Velemeny { get; set; }
        public bool Lattamozott { get; set; }

    }
}

Szakdoga/Controllers/IntezoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Szakdoga.Models;

namespace Szakdoga.Controllers
{
    public class IntezoController : Controller
    {
        // GET: MessageShow
        readonly ApplicationDbContext _context;
        public IntezoController() => _context = new ApplicationDbContext();

        public ActionResult Index()
        {
            var messages = _context.Messages.ToList().OrderByDescending(f => f.Id);
            return View(messages);
        }
        public ActionResult Torles(int id)
        {
            var message = _context.Messages.Find(id);
            if (message == null) return HttpNotFound();
            _context.Messages.Remove(message);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Szakdoga/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Naptárkezelő Alkalmazás</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Naptárkezelő Alkalmazás</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Szakdoga/Views/Shared/_Message.cshtml
@model Szakdoga.Models.Message

<div class="col-md-auto">
    <div class="card" style="width:auto;height:auto;margin-top:20px;">
        <div class="card-header" style="font-weight:bold;font-style:italic;background: linear-gradient(to right, #007bff, #fff);color: white;">
            <h4 style="font-weight: bold; ">@Model.Email</h4>
        </div>
        <div class="card-body cardborder">
            <blockquote class="blockquote mb-0">
                <p>@Model.Velemeny</p>
                @if (User.IsInRole("Admin"))
                {
                    <span onclick="return confirm('Törlöd?')" style="float:right;">@Html.ActionLink("Törlés", "Torles", "Intezo", new { id = Model.Id }, new { @class = "btn btn-outline-danger" })</span>
                }
            </blockquote>
        </div>
    </div>
</div>

Szakdoga/Views/Shared/_NavBar.cshtml
@using Szakdoga.Models
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    @Html.ActionLink("Naptár", "Calendar", "Home", new { area = "" }, new { @class = "navbar-brand" })

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            @if (User.IsInRole(Szakdoga.Models.RoleNevek.Admin))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Menedzsment
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/Users/UserIndex">Felhasználók</a>
                        <a class="dropdown-item" href="/Home/Event">Események</a>

                    </div>
                </li>
            }
            @if (User.IsInRole(Szakdoga.Models.RoleNevek.User))
            {
            <li class="nav-item">
                <a class=" nav-link" href="/Uzenet/New">Új üzenet</a>
            </li>
            }
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>